
const C=["#2563eb","#7c3aed","#0891b2","#16a34a","#ea580c","#dc2626","#4f46e5","#0f766e"];
const eur=v=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v);
const pct=v=>new Intl.NumberFormat("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)+" %";
const nfmt=v=>new Intl.NumberFormat("de-DE",{maximumFractionDigits:2}).format(v);
const latest=D.depot.at(-1),start=D.depot[0],low=Math.min(...D.depot),high=Math.max(...D.depot),lastDelta=latest-D.depot.at(-2);
const allSeries={...D.core,...D.savings};
const insightPanel=document.getElementById("insightPanel"),appLayout=document.querySelector(".app-layout");
let selectedSale=new Set(D.positions.filter(p=>p.pl>0).map(p=>p.name));
let cashMode="gain";
let scenarioPct=0;

const EXPLAIN={
development:{what:"Der Verlauf zeigt den gesamten dokumentierten Depotwert zu jedem Screenshot-Zeitpunkt.",how:"Jeder Punkt entspricht dem Gesamtwert aus einem Screenshot. Die Veränderung ergibt sich aus aktuellem minus vorherigem Messpunkt.",why:"So erkennst du Trend, Hochpunkte, Rückgänge und die Geschwindigkeit der Erholung."},
allocation:{what:"Die Depotstruktur zeigt, wie stark die einzelnen Anlagekategorien gewichtet sind.",how:"Kategorieanteil = Wert der Kategorie ÷ Gesamtdepot.",why:"Eine sehr große Kategorie kann die Entwicklung dominieren und erhöht das Konzentrationsrisiko."},
weekly:{what:"Der Wochenvergleich betrachtet die Veränderung seit dem letzten dokumentierten Screenshot.",how:"Letzter Wert minus vorheriger Wert.",why:"Er zeigt kurzfristige Bewegung, ohne sie mit der langfristigen Rendite zu verwechseln."},
ranking:{what:"Gewinner und Verlierer ordnen die Positionen nach ihrer letzten absoluten Veränderung.",how:"Positionswert heute minus Positionswert beim vorherigen Messpunkt.",why:"Du erkennst, welche Positionen die aktuelle Depotbewegung tatsächlich verursachen."},
indexed:{what:"Alle Hauptpositionen starten rechnerisch bei 100.",how:"Index = Positionswert ÷ Wert am ersten Messpunkt × 100.",why:"Dadurch lassen sich große und kleine Positionen fair nach relativer Entwicklung vergleichen."},
positions:{what:"Jede Karte zeigt aktuellen Wert, letzte Veränderung und Abstand zum bisherigen Hoch.",how:"Die Werte stammen aus der gespeicherten Zeitreihe der jeweiligen Position.",why:"So erkennst du nicht nur Gewinn, sondern auch Momentum und Rückschlagrisiko."},
drawdown:{what:"Der Drawdown misst den Rückgang vom jeweils vorher erreichten Höchststand.",how:"Drawdown = aktueller Wert ÷ bisheriges Hoch − 1.",why:"Er beschreibt das tatsächlich erlebte Verlustrisiko besser als eine reine Renditezahl."},
savings:{what:"Der Sparplanvergleich trennt Einzahlungen von Marktgewinnen.",how:"Kursgewinn = aktueller Sparplanwert minus kumulierte Einzahlung.",why:"Ein steigender Wert ist nicht automatisch Gewinn, wenn gleichzeitig neue Raten eingezahlt wurden."},
monthly:{what:"Die Monatsdarstellung vergleicht ersten und letzten Messpunkt jedes Monats.",how:"Monatsänderung = Monatsendwert minus Monatsanfangswert.",why:"Sie glättet einzelne Tage und macht stärkere Phasen sichtbar."},
profitAccount:{what:"Das Gewinnkonto ist der aktuelle Depotwert oberhalb des investierten Kapitals.",how:"Gewinnkonto = Summe aktueller Positionswerte minus Summe investiertes Kapital.",why:"Es zeigt den Buchgewinn. Erst durch Verkauf wird daraus verfügbares Geld."},
tax:{what:"Die Steuerannahmen schätzen den möglichen Abzug bei einem Verkauf.",how:"Steuerpflichtiger Gewinn wird um Teilfreistellung und verfügbaren Pauschbetrag reduziert. Darauf werden Abgeltungsteuer, Solidaritätszuschlag und optional Kirchensteuer simuliert.",why:"Bruttogewinn und tatsächlich verfügbarer Nettozufluss können deutlich auseinanderliegen. Die Berechnung ist bewusst anpassbar."},
sale:{what:"Der Simulator verkauft den gewählten Prozentsatz jeder markierten Position.",how:"Verkaufserlös und Einstand werden proportional angesetzt. Nur der realisierte positive Gewinn wird nach den eingestellten Annahmen besteuert.",why:"Du siehst, wie viel Geld tatsächlich zufließen könnte und wie groß das Restdepot bleibt."},
cash:{what:"Der Cash-Generator sucht eine Kombination von Teilverkäufen für ein gewünschtes Nettoziel.",how:"Je nach Modus werden Positionen nach Gewinn, Depotgewicht oder Risikoreduktion priorisiert und schrittweise verkauft.",why:"Er übersetzt die Frage 'Ich brauche X Euro' in einen nachvollziehbaren Verkaufsvorschlag."},
protection:{what:"Gewinnschutz simuliert einen prozentualen Rückgang jeder Position.",how:"Simulierter Wert = aktueller Wert × (1 − Rückgang). Verbleibender Gewinn = simulierter Wert − investiertes Kapital.",why:"Du erkennst, welche Buchgewinne schon robust sind und welche bei einer normalen Korrektur verschwinden könnten."},
rebalance:{what:"Der Rebalancing-Assistent sucht übergewichtete Positionen und Kategorien.",how:"Er vergleicht Ist-Gewichte mit einer neutralen Zielverteilung innerhalb der vorhandenen Kategorien.",why:"Teilverkauf kann nicht nur Gewinn sichern, sondern auch die Abhängigkeit von einzelnen Positionen reduzieren."},
marketScenario:{what:"Das Marktszenario verändert alle aktuellen Positionen um denselben Prozentsatz.",how:"Szenariowert = aktueller Positionswert × (1 + Szenarioprozent).",why:"Es ist keine Prognose, sondern ein Belastungs- oder Chancencheck für das Gesamtdepot."},
future:{what:"Die Zukunftssimulation verbindet Startvermögen, monatliche Rate und angenommene Rendite.",how:"Monatliche Verzinsung mit regelmäßiger Einzahlung über den gewählten Zeitraum.",why:"Sie zeigt den Einfluss von Zeit und Sparrate, nicht die Wahrscheinlichkeit eines konkreten Ergebnisses."},
monteCarlo:{what:"Die vereinfachte Monte-Carlo-Spanne zeigt eine mögliche Bandbreite künftiger Ergebnisse.",how:"Aus Renditeannahme und Volatilität werden viele deterministisch reproduzierbare Zufallspfade berechnet. Angezeigt werden 10., 50. und 90. Perzentil.",why:"Eine Bandbreite ist ehrlicher als eine einzelne Zukunftszahl. Dennoch bleibt es ein Modell ohne Garantie."},
portfolioGoal:{what:"Der Zielmonitor vergleicht aktuellen Depotwert mit deinem Zielwert.",how:"Fortschritt = aktueller Depotwert ÷ Zielwert.",why:"Das macht den langfristigen Vermögensaufbau messbar."},
profitGoal:{what:"Das Gewinnziel misst nur den Buchgewinn oberhalb des eingesetzten Kapitals.",how:"Fortschritt = aktuelles Gewinnkonto ÷ Zielgewinn.",why:"So kannst du ein konkretes Niveau definieren, ab dem eine Gewinnmitnahme geprüft wird."},
health:{what:"Der Health Score ist ein transparenter Orientierungswert von 0 bis 100.",how:"Er kombiniert Diversifikation, Konzentration, Rendite, Drawdown und Sparplandisziplin mit festen Gewichtungen.",why:"Er ersetzt keine Anlageberatung, fasst aber mehrere Qualitätsdimensionen verständlich zusammen."},
lifeGoals:{what:"Der Alltagsbezug übersetzt geschätzten Nettogewinn in konkrete Verwendungszwecke.",how:"Nettogewinn wird durch Kreditrate, Sparplanrate oder Urlaubskosten geteilt.",why:"So wird aus einer abstrakten Rendite eine verständliche finanzielle Möglichkeit."},
journal:{what:"Das Tagebuch formuliert aus jedem Screenshot einen chronologischen Eintrag.",how:"Depotwert, Veränderung, Gewinner, Verlierer und vorhandene Notizen werden zusammengeführt.",why:"Du kannst später nachvollziehen, wie sich das Vermögen entwickelt hat und welche Phasen prägend waren."}
};

function learningHtml(key){const e=EXPLAIN[key];return `<h4>Was sehe ich?</h4><p>${e.what}</p><h4>Wie wird gerechnet?</h4><p>${e.how}</p><h4>Warum ist das wichtig?</h4><p>${e.why}</p>`}
document.querySelectorAll(".learn-box").forEach(el=>el.innerHTML=learningHtml(el.dataset.learning));
document.body.classList.add("learning-on");

function setInsight(type,title,html){document.getElementById("insightType").textContent=type;document.getElementById("insightTitle").textContent=title;document.getElementById("insightBody").innerHTML=html;appLayout.classList.add("insight-open")}
function miniSpark(values,color="#60a5fa"){const W=290,H=120,p=6,lo=Math.min(...values),hi=Math.max(...values),x=i=>p+i*(W-2*p)/Math.max(1,values.length-1),y=v=>p+(hi-v)*(H-2*p)/((hi-lo)||1);return `<svg class="insight-chart" viewBox="0 0 ${W} ${H}"><polyline points="${values.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function showExplanation(key){const e=EXPLAIN[key];setInsight("Erklärung",document.querySelector(`[data-explain="${key}"]`)?.closest(".card")?.querySelector("h2")?.textContent||"Simulation",`<div class="insight-section"><div class="insight-label">Was sehe ich?</div><p>${e.what}</p></div><div class="insight-section"><div class="insight-label">Wie wird gerechnet?</div><p>${e.how}</p></div><div class="insight-section"><div class="insight-label">Warum ist das wichtig?</div><p>${e.why}</p></div>`)}
document.querySelectorAll(".explain-btn").forEach(b=>b.onclick=()=>showExplanation(b.dataset.explain));

function lineChart(id,labels,series,{percent=false,zero=false,globalOffset=0,onPoint=null}={}){
 const svg=document.getElementById(id),W=+svg.viewBox.baseVal.width,H=+svg.viewBox.baseVal.height,p={l:64,r:18,t:18,b:42};let vals=series.flatMap(s=>s.values),lo=Math.min(...vals),hi=Math.max(...vals);if(zero){lo=Math.min(lo,0);hi=Math.max(hi,0)}const pad=(hi-lo)*.1||1;lo-=pad;hi+=pad;const x=i=>p.l+i*(W-p.l-p.r)/Math.max(1,labels.length-1),y=v=>p.t+(hi-v)*(H-p.t-p.b)/(hi-lo);let out="";
 for(let i=0;i<5;i++){const v=lo+i*(hi-lo)/4,yy=y(v);out+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="var(--line)"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end" fill="var(--muted)" font-size="10">${percent?pct(v):Math.round(v/1000)+"k"}</text>`}
 labels.forEach((d,i)=>{if(i===0||i===labels.length-1||i%3===0)out+=`<text x="${x(i)}" y="${H-14}" text-anchor="middle" fill="var(--muted)" font-size="10">${d}</text>`});
 series.forEach((s,si)=>{const points=s.values.map((v,i)=>`${x(i)},${y(v)}`).join(" ");out+=`<polyline points="${points}" fill="none" stroke="${C[si%C.length]}" stroke-width="${s.bold?3.4:2.4}"/>`;s.values.forEach((v,i)=>out+=`<circle class="chart-point" data-series="${si}" data-index="${i}" cx="${x(i)}" cy="${y(v)}" r="8" fill="transparent"/><circle cx="${x(i)}" cy="${y(v)}" r="3" fill="${C[si%C.length]}" stroke="white"/>`)});
 svg.innerHTML=out;svg.querySelectorAll(".chart-point").forEach(point=>point.onclick=()=>{const si=+point.dataset.series,i=+point.dataset.index,s=series[si];if(onPoint)onPoint(s,i);else showChartInsight(s,labels,i,globalOffset+i)});
}
function hbars(id,rows,key,fmt,signed=false){
 const svg=document.getElementById(id),W=+svg.viewBox.baseVal.width,H=+svg.viewBox.baseVal.height,padX=14,padY=10,rowH=(H-padY*2)/rows.length,max=Math.max(...rows.map(r=>Math.abs(r[key])))||1,left=padX,right=W-padX,center=(left+right)/2;let out="";
 rows.forEach((r,i)=>{const y=padY+i*rowH,labelY=y+11,trackY=y+18,trackH=Math.max(7,Math.min(11,rowH-24)),value=r[key],fullW=right-left;let x=left,w=Math.abs(value)/max*fullW,barColor="#2563eb";if(signed){const half=(fullW-10)/2;w=Math.abs(value)/max*half;x=value>=0?center+5:center-5-w;barColor=value>=0?"#15803d":"#b91c1c";out+=`<line class="bar-chart-zero" x1="${center}" y1="${trackY-2}" x2="${center}" y2="${trackY+trackH+2}"/><rect class="bar-chart-track" x="${left}" y="${trackY}" width="${half}" height="${trackH}" rx="${trackH/2}"/><rect class="bar-chart-track" x="${center+5}" y="${trackY}" width="${half}" height="${trackH}" rx="${trackH/2}"/>`}else out+=`<rect class="bar-chart-track" x="${left}" y="${trackY}" width="${fullW}" height="${trackH}" rx="${trackH/2}"/>`;out+=`<text class="bar-chart-label" x="${left}" y="${labelY}">${r.name}</text><text class="bar-chart-value" x="${right}" y="${labelY}" text-anchor="end">${fmt(value)}</text><rect x="${x}" y="${trackY}" width="${Math.max(w,2)}" height="${trackH}" rx="${trackH/2}" fill="${barColor}"/><rect class="bar-hit" data-index="${i}" x="${left}" y="${y}" width="${fullW}" height="${rowH}" fill="transparent"/>`});
 svg.innerHTML=out;svg.querySelectorAll(".bar-hit").forEach(hit=>hit.onclick=()=>{const r=rows[+hit.dataset.index];if(D.positions.some(p=>p.name===r.name))showPositionInsight(r.name)});
}
function sparkline(values){const W=220,H=54,p=3,lo=Math.min(...values),hi=Math.max(...values),x=i=>p+i*(W-2*p)/(values.length-1),y=v=>p+(hi-v)*(H-2*p)/((hi-lo)||1);return `<svg class="spark" viewBox="0 0 ${W} ${H}"><polyline points="${values.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="#2563eb" stroke-width="2.4"/></svg>`}

function showPortfolioInsight(){const invested=D.positions.reduce((a,p)=>a+p.invested,0),profit=latest-invested,best=[...D.positions].sort((a,b)=>b.perf-a.perf)[0],worst=[...D.positions].sort((a,b)=>a.perf-b.perf)[0];setInsight("Portfolio Insight","Gesamtübersicht",`<div class="insight-section"><div class="insight-label">Aktueller Depotwert</div><div class="insight-value">${eur(latest)}</div><div class="${lastDelta>=0?"pos":"neg"}">${lastDelta>=0?"+":""}${eur(lastDelta)} seit letztem Screenshot</div>${miniSpark(D.depot)}</div><div class="insight-section"><div class="insight-grid"><div class="insight-stat"><span>Investiert</span><strong>${eur(invested)}</strong></div><div class="insight-stat"><span>Gewinnkonto</span><strong>${eur(profit)}</strong></div><div class="insight-stat"><span>Beste Position</span><strong>${best.name}</strong></div><div class="insight-stat"><span>Schwächste Position</span><strong>${worst.name}</strong></div></div></div>`)}
function showPositionInsight(name){const p=D.positions.find(x=>x.name===name),arr=allSeries[name],peak=Math.max(...arr),weekly=arr.at(-1)-arr.at(-2);setInsight("Position Insight",name,`<div class="insight-section"><div class="insight-label">Aktueller Wert</div><div class="insight-value">${eur(p.value)}</div><div class="${p.perf>=0?"pos":"neg"}">${p.perf>=0?"+":""}${pct(p.perf)} seit Kauf</div>${miniSpark(arr,p.perf>=0?"#86efac":"#fda4af")}</div><div class="insight-section"><div class="insight-grid"><div class="insight-stat"><span>Investiert</span><strong>${eur(p.invested)}</strong></div><div class="insight-stat"><span>G/V</span><strong>${eur(p.pl)}</strong></div><div class="insight-stat"><span>Woche</span><strong>${eur(weekly)}</strong></div><div class="insight-stat"><span>Abstand Hoch</span><strong>${pct((p.value/peak-1)*100)}</strong></div></div></div>`)}
function showChartInsight(series,labels,i,gi){const v=series.values[i],prev=i>0?series.values[i-1]:null;setInsight("Chart Insight",series.name,`<div class="insight-section"><div class="insight-label">Messpunkt</div><div class="insight-value">${eur(v)}</div><div class="${prev===null?"":v-prev>=0?"pos":"neg"}">${prev===null?"Startpunkt":`${v-prev>=0?"+":""}${eur(v-prev)}`}</div></div><div class="insight-grid"><div class="insight-stat"><span>Datum</span><strong>${D.fullDates[gi]||labels[i]}</strong></div><div class="insight-stat"><span>Seit Start</span><strong>${pct((v/series.values[0]-1)*100)}</strong></div></div>`)}
function showCategoryInsight(c){const total=D.categories.reduce((a,b)=>a+b.value,0),ps=D.positions.filter(p=>p.cat===c.name);setInsight("Category Insight",c.name,`<div class="insight-value">${eur(c.value)}</div><div>${pct(c.value/total*100)} des Gesamtdepots</div><div class="insight-list">${ps.map(p=>`<div class="insight-list-row"><span>${p.name}</span><strong>${eur(p.value)}</strong></div>`).join("")}</div>`)}

document.getElementById("rangeLabel").textContent=D.dates[0]+"–"+D.meta.lastUpdate;
document.getElementById("kpis").innerHTML=[["Aktueller Depotwert",eur(latest),"Stand "+D.meta.lastUpdate],["Seit Start",eur(latest-start),pct((latest/start-1)*100)],["Seit letztem Screenshot",eur(lastDelta),pct((latest/D.depot.at(-2)-1)*100)],["Erholung seit Tief",eur(latest-low),pct((latest/low-1)*100)]].map((x,i)=>`<article class="card kpi"><div class="label">${x[0]}</div><div class="value ${x[1].startsWith("-")?"neg":(i>0?"pos":"")}">${x[1]}</div><div class="hint">${x[2]}</div></article>`).join("");
lineChart("depotChart",D.dates,[{name:"Depotwert",values:D.depot,bold:true}]);
document.getElementById("weeklyKpis").innerHTML=[["Depotveränderung",eur(lastDelta)],["Monatsveränderung",eur(latest-D.monthly.at(-1).start)],["Bester Wert",D.weeklyChanges[0].name],["Schwächster Wert",D.weeklyChanges.at(-1).name]].map(x=>`<div class="mini-card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");
document.getElementById("ranking").innerHTML=`<div class="rank-list">${D.weeklyChanges.slice(0,3).map((r,i)=>`<div class="rank-item" data-name="${r.name}"><span>${i+1}. ${r.name}</span><strong class="${r.change>=0?"pos":"neg"}">${eur(r.change)}</strong></div>`).join("")}<div style="height:8px"></div>${D.weeklyChanges.slice(-3).reverse().map((r,i)=>`<div class="rank-item" data-name="${r.name}"><span>${i+1}. ${r.name}</span><strong class="${r.change>=0?"pos":"neg"}">${eur(r.change)}</strong></div>`).join("")}</div>`;document.querySelectorAll(".rank-item").forEach(el=>el.onclick=()=>showPositionInsight(el.dataset.name));
const normalized={};Object.entries(D.core).forEach(([k,v])=>normalized[k]=v.map(x=>x/v[0]*100));const names=Object.keys(normalized);document.getElementById("coreTabs").innerHTML='<button class="active" data-mode="all">Alle</button>'+names.map((n,i)=>`<button data-mode="${i}">${n}</button>`).join("");function drawCore(mode="all"){const s=mode==="all"?names.map(n=>({name:n,values:normalized[n]})):[{name:names[+mode],values:normalized[names[+mode]],bold:true}];lineChart("coreChart",D.dates,s);document.getElementById("coreLegend").innerHTML=s.map((x,i)=>`<span><i style="background:${C[i]}"></i>${x.name}</span>`).join("")}drawCore();document.querySelectorAll("#coreTabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#coreTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");drawCore(b.dataset.mode)});
document.getElementById("positionCards").innerHTML=D.positions.map(p=>{const arr=allSeries[p.name],peak=Math.max(...arr),dist=(p.value/peak-1)*100,weekly=arr.at(-1)-arr.at(-2);return `<div class="position-card" data-name="${p.name}"><h3>${p.name}</h3>${sparkline(arr)}<div class="row"><span>Aktueller Wert</span><strong>${eur(p.value)}</strong></div><div class="row"><span>Seit letzter Woche</span><strong class="${weekly>=0?"pos":"neg"}">${eur(weekly)}</strong></div><div class="row"><span>Abstand zum Hoch</span><strong>${pct(dist)}</strong></div></div>`}).join("");document.querySelectorAll(".position-card").forEach(c=>c.onclick=()=>showPositionInsight(c.dataset.name));
let rm=-Infinity,maxDD=0,maxDDi=0;const dd=D.depot.map((v,i)=>{rm=Math.max(rm,v);const d=(v/rm-1)*100;if(d<maxDD){maxDD=d;maxDDi=i}return d});lineChart("drawdownChart",D.dates,[{name:"Drawdown",values:dd,bold:true}],{percent:true,zero:true});document.getElementById("drawdownFacts").innerHTML=[["Größter Rückgang",pct(maxDD)],["Tiefpunkt",D.dates[maxDDi]],["Aktueller Abstand",pct((latest/high-1)*100)],["Hochpunkt",D.dates[D.depot.indexOf(high)]]].map(x=>`<div class="fact"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");
const sn=Object.keys(D.savings);document.getElementById("savingTabs").innerHTML=sn.map((n,i)=>`<button class="${i===0?"active":""}" data-i="${i}">${n}</button>`).join("");function drawSaving(i=0){const n=sn[i],v=D.savings[n],invested=D.contrib.at(-1),current=v.at(-1),gain=current-invested;lineChart("savingsChart",D.dates,[{name:n,values:v,bold:true},{name:"Einzahlungen",values:D.contrib}]);document.getElementById("savingFacts").innerHTML=[["Eingezahlt",eur(invested)],["Aktueller Wert",eur(current)],["Kursgewinn/-verlust",eur(gain)],["Rendite",pct(gain/invested*100)]].map(x=>`<div class="fact"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("")}drawSaving();document.querySelectorAll("#savingTabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#savingTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");drawSaving(+b.dataset.i)});
hbars("monthlyChart",D.monthly.map(m=>({name:m.month.slice(5)+"/"+m.month.slice(2,4),value:m.change})),"value",eur,true);
(function donut(){const svg=document.getElementById("donut"),cx=210,cy=155,r=100,sw=48,total=D.categories.reduce((a,b)=>a+b.value,0);let acc=0,out="";D.categories.forEach((c,i)=>{const f=c.value/total,len=2*Math.PI*r*f,off=-2*Math.PI*r*acc;out+=`<circle class="donut-segment" data-index="${i}" cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${C[i]}" stroke-width="${sw}" stroke-dasharray="${len} ${2*Math.PI*r-len}" stroke-dashoffset="${off}" transform="rotate(-90 ${cx} ${cy})"/>`;acc+=f});out+=`<text x="${cx}" y="${cy-4}" text-anchor="middle" fill="var(--muted)" font-size="13">Depotwert</text><text x="${cx}" y="${cy+24}" text-anchor="middle" fill="var(--ink)" font-size="21" font-weight="800">${Math.round(total/1000)} Tsd. €</text>`;svg.innerHTML=out;svg.querySelectorAll(".donut-segment").forEach(seg=>seg.onclick=()=>showCategoryInsight(D.categories[+seg.dataset.index]));document.getElementById("catLegend").innerHTML=D.categories.map((c,i)=>`<span><i style="background:${C[i]}"></i>${c.name} · ${pct(c.value/total*100)}</span>`).join("")})();

// TAX AND STRATEGY
function taxSettings(){return{tax:+document.getElementById("taxRate")?.value||D.defaults.taxRate,soli:+document.getElementById("soliRate")?.value||D.defaults.solidarityRate,church:+document.getElementById("churchRate")?.value||0,allowance:+document.getElementById("allowance")?.value||0,cost:+document.getElementById("sellCost")?.value||0}}
function calculateTax(gain,exemption,allowanceShare,settings){if(gain<=0)return{taxable:0,tax:0};const afterExemption=gain*(1-exemption/100);const taxable=Math.max(0,afterExemption-allowanceShare);const baseTax=taxable*settings.tax/100;const soli=baseTax*settings.soli/100;const church=baseTax*settings.church/100;return{taxable,tax:baseTax+soli+church}}
const investedTotal=D.positions.reduce((a,p)=>a+p.invested,0),profitTotal=latest-investedTotal;
function renderProfitAccount(){const ratio=Math.max(0,Math.min(100,profitTotal/latest*100));const html=`<div class="account-bar"><span style="width:${ratio}%"></span></div><div class="account-legend"><span>Investiertes Kapital ${eur(investedTotal)}</span><span>Gewinn ${eur(profitTotal)}</span></div><div class="fact-grid"><div class="fact"><div class="label">Depotwert</div><div class="value">${eur(latest)}</div></div><div class="fact"><div class="label">Gewinnquote</div><div class="value">${pct(profitTotal/latest*100)}</div></div></div>`;document.getElementById("profitAccount").innerHTML=html;document.getElementById("profitAccountHero").innerHTML=`<span>Aktuelles Gewinnkonto</span><strong>${eur(profitTotal)}</strong><small>${pct(profitTotal/investedTotal*100)} auf investiertes Kapital</small>`}
renderProfitAccount();
document.getElementById("taxSettings").innerHTML=`<div class="input-line"><label>Abgeltungsteuer %</label><input id="taxRate" type="number" step="0.1" value="${D.defaults.taxRate}"></div><div class="input-line"><label>Solidaritätszuschlag auf Steuer %</label><input id="soliRate" type="number" step="0.1" value="${D.defaults.solidarityRate}"></div><div class="input-line"><label>Kirchensteuer %</label><input id="churchRate" type="number" step="1" value="${D.defaults.churchTaxRate}"></div><div class="input-line"><label>Verbleibender Pauschbetrag</label><input id="allowance" type="number" step="100" value="${D.defaults.allowanceRemaining}"></div><div class="input-line"><label>Verkaufskosten %</label><input id="sellCost" type="number" step="0.05" value="${D.defaults.sellingCostsRate}"></div>`;
document.getElementById("salePositionPicker").innerHTML=D.positions.map(p=>`<label class="position-check"><input type="checkbox" data-name="${p.name}" ${selectedSale.has(p.name)?"checked":""}>${p.name}</label>`).join("");
document.querySelectorAll("#salePositionPicker input").forEach(i=>i.onchange=()=>{i.checked?selectedSale.add(i.dataset.name):selectedSale.delete(i.dataset.name);renderSale()});
function simulateSale(p,salePct,allowanceShare,settings){const fraction=salePct/100,gross=p.value*fraction,basis=p.invested*fraction,gain=gross-basis,cost=gross*settings.cost/100,t=calculateTax(gain,p.taxExemption,allowanceShare,settings),net=gross-cost-t.tax;return{gross,basis,gain,cost,tax:t.tax,net,rest:p.value-gross}}
function renderSale(){const salePct=+document.getElementById("salePct").value,settings=taxSettings(),positiveSelected=D.positions.filter(p=>selectedSale.has(p.name)&&p.pl>0),rawTaxable=positiveSelected.reduce((a,p)=>a+Math.max(0,p.pl*salePct/100*(1-p.taxExemption/100)),0);let rows=[],tot={gross:0,gain:0,tax:0,net:0,rest:0,cost:0};D.positions.filter(p=>selectedSale.has(p.name)).forEach(p=>{const taxablePotential=Math.max(0,p.pl*salePct/100*(1-p.taxExemption/100)),share=rawTaxable?settings.allowance*taxablePotential/rawTaxable:0,r=simulateSale(p,salePct,share,settings);rows.push({p,...r});Object.keys(tot).forEach(k=>tot[k]+=r[k]||0)});document.getElementById("salePctLabel").textContent=salePct+" %";document.getElementById("saleSummary").innerHTML=[["Bruttoerlös",tot.gross],["Realisierter Gewinn",tot.gain],["Kosten",tot.cost],["Steuer geschätzt",tot.tax],["Nettozufluss",tot.net]].map(x=>`<div class="summary-cell"><span>${x[0]}</span><strong>${eur(x[1])}</strong></div>`).join("");document.getElementById("saleRows").innerHTML=rows.map(r=>`<tr><td>${r.p.name}</td><td>${eur(r.gross)}</td><td class="${r.gain>=0?"pos":"neg"}">${eur(r.gain)}</td><td>${eur(r.tax)}</td><td><strong>${eur(r.net)}</strong></td><td>${eur(r.rest)}</td></tr>`).join("")}
document.getElementById("salePct").oninput=renderSale;document.querySelectorAll("#taxSettings input").forEach(i=>i.oninput=()=>{renderSale();renderCash();renderGoals()});renderSale();

function saleNetFor(p,amount,settings,allowanceLeft){const fraction=Math.min(1,amount/p.value),gross=p.value*fraction,basis=p.invested*fraction,gain=gross-basis,cost=gross*settings.cost/100,t=calculateTax(gain,p.taxExemption,Math.min(allowanceLeft,Math.max(0,gain*(1-p.taxExemption/100))),settings);return{fraction,gross,gain,tax:t.tax,cost,net:gross-cost-t.tax,allowanceUsed:Math.min(allowanceLeft,Math.max(0,gain*(1-p.taxExemption/100)))}}
function renderCash(){const target=+document.getElementById("cashTarget").value||0,settings=taxSettings();let order=[...D.positions];if(cashMode==="gain")order.sort((a,b)=>b.perf-a.perf);if(cashMode==="risk")order.sort((a,b)=>b.value-a.value);if(cashMode==="balanced")order.sort((a,b)=>b.value-a.value);let needed=target,allowance=settings.allowance,result=[];for(const p of order){if(needed<=1)break;if(cashMode==="gain"&&p.pl<=0)continue;let guess=Math.min(p.value,needed*1.15);let r=saleNetFor(p,guess,settings,allowance);if(r.net>needed){guess*=needed/r.net;r=saleNetFor(p,guess,settings,allowance)}result.push({p,...r});needed-=r.net;allowance-=r.allowanceUsed}const net=result.reduce((a,r)=>a+r.net,0),gross=result.reduce((a,r)=>a+r.gross,0);document.getElementById("cashResult").innerHTML=`<div class="fact-grid"><div class="fact"><div class="label">Erwarteter Nettozufluss</div><div class="value">${eur(net)}</div></div><div class="fact"><div class="label">Bruttoverkauf</div><div class="value">${eur(gross)}</div></div></div>${result.map(r=>`<div class="recommendation"><strong>${pct(r.fraction*100)} von ${r.p.name}</strong><p>Brutto ${eur(r.gross)}, Netto geschätzt ${eur(r.net)}.</p></div>`).join("")}${needed>1?`<div class="recommendation" style="border-left-color:var(--red)"><strong>Ziel nicht vollständig erreichbar</strong><p>Es fehlen noch ${eur(needed)} mit den Regeln dieses Modus.</p></div>`:""}`}
document.getElementById("cashTarget").oninput=renderCash;document.querySelectorAll("#cashStrategy button").forEach(b=>b.onclick=()=>{cashMode=b.dataset.mode;b.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderCash()});renderCash();

function renderProtection(){const drop=+document.getElementById("protectionDrop").value;document.getElementById("protectionLabel").textContent="−"+drop+" %";document.getElementById("protectionGrid").innerHTML=D.positions.map(p=>{const simulated=p.value*(1-drop/100),remaining=simulated-p.invested,originalPositive=Math.max(0,p.pl),survival=originalPositive?Math.max(0,remaining)/originalPositive*100:0,color=remaining>0?"#15803d":remaining>-p.invested*.03?"#b45309":"#b91c1c";return `<div class="protection-row"><div class="protection-head"><strong>${p.name}</strong><span class="${remaining>=0?"pos":"neg"}">${eur(remaining)} Restgewinn</span></div><div class="protection-track"><span style="width:${Math.min(100,survival)}%;background:${color}"></span></div></div>`}).join("")}
document.getElementById("protectionDrop").oninput=renderProtection;renderProtection();

function renderRebalance(){const total=latest,categoryTarget=25;let recommendations=[];D.categories.forEach(c=>{const share=c.value/total*100;if(share>categoryTarget+7){const excess=c.value-total*categoryTarget/100;recommendations.push({title:`${c.name} ist mit ${pct(share)} stark gewichtet`,text:`Ein theoretischer Verkauf von rund ${eur(excess)} würde die Kategorie näher an 25 % bringen.`})}});const largest=[...D.positions].sort((a,b)=>b.value-a.value)[0],share=largest.value/total*100;if(share>30)recommendations.push({title:`${largest.name} prägt ${pct(share)} des Depots`,text:`Eine Teilreduzierung um 5–10 % der Position könnte Konzentration senken, ohne sie aufzugeben.`});document.getElementById("rebalanceResult").innerHTML=recommendations.length?recommendations.map(r=>`<div class="recommendation"><strong>${r.title}</strong><p>${r.text}</p></div>`).join(""):`<div class="recommendation"><strong>Keine starke Übergewichtung erkannt</strong><p>Die aktuelle Verteilung liegt innerhalb der vereinfachten Toleranz.</p></div>`}
renderRebalance();

// SCENARIOS
document.getElementById("scenarioButtons").innerHTML=[-20,-10,-5,0,5,10,20].map(v=>`<button data-v="${v}" class="${v===0?"active":""}">${v>0?"+":""}${v} %</button>`).join("");
function renderScenario(){const value=latest*(1+scenarioPct/100),profit=value-investedTotal;document.getElementById("scenarioSummary").innerHTML=`<div class="scenario-kpis"><div class="fact"><div class="label">Szenario-Depotwert</div><div class="value">${eur(value)}</div></div><div class="fact"><div class="label">Gewinnkonto danach</div><div class="value ${profit>=0?"pos":"neg"}">${eur(profit)}</div></div><div class="fact"><div class="label">Veränderung</div><div class="value">${eur(value-latest)}</div></div></div>`;hbars("scenarioChart",D.positions.map(p=>({name:p.name,value:p.value*(1+scenarioPct/100)-p.invested})),"value",eur,true)}
document.querySelectorAll("#scenarioButtons button").forEach(b=>b.onclick=()=>{scenarioPct=+b.dataset.v;b.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderScenario()});renderScenario();

function futureValues(){const monthly=+document.getElementById("futureSaving").value,annual=+document.getElementById("futureReturn").value/100,years=+document.getElementById("futureYears").value;let vals=[latest],v=latest;for(let y=1;y<=years;y++){for(let m=0;m<12;m++)v=v*(1+annual/12)+monthly;vals.push(v)}return{monthly,annual,years,vals}}
function renderFuture(){const f=futureValues(),labels=Array.from({length:f.years+1},(_,i)=>String(2026+i)),deposits=f.monthly*12*f.years,growth=f.vals.at(-1)-latest-deposits;document.getElementById("futureSavingLabel").textContent=eur(f.monthly);document.getElementById("futureReturnLabel").textContent=pct(f.annual*100);document.getElementById("futureYearsLabel").textContent=f.years+" Jahre";document.getElementById("futureFacts").innerHTML=[["Endwert",eur(f.vals.at(-1))],["Neue Einzahlungen",eur(deposits)],["Modellwachstum",eur(growth)],["Zeitraum",f.years+" Jahre"]].map(x=>`<div class="fact"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");lineChart("futureChart",labels,[{name:"Neutral",values:f.vals,bold:true}])}
["futureSaving","futureReturn","futureYears"].forEach(id=>document.getElementById(id).oninput=()=>{renderFuture();renderMC()});renderFuture();

function seededRandom(seed){let x=Math.sin(seed)*10000;return x-Math.floor(x)}
function renderMC(){const f=futureValues(),vol=+document.getElementById("volatility").value/100,paths=400,finals=[],yearBuckets=Array.from({length:f.years+1},()=>[]);for(let p=0;p<paths;p++){let v=latest;yearBuckets[0].push(v);for(let y=1;y<=f.years;y++){for(let m=0;m<12;m++){const u1=Math.max(1e-9,seededRandom(p*10000+y*100+m*2)),u2=seededRandom(p*10000+y*100+m*2+1),z=Math.sqrt(-2*Math.log(u1))*Math.cos(2*Math.PI*u2),monthlyReturn=f.annual/12+vol/Math.sqrt(12)*z;v=Math.max(0,v*(1+monthlyReturn)+f.monthly)}yearBuckets[y].push(v)}finals.push(v)}const quant=(arr,q)=>{const s=[...arr].sort((a,b)=>a-b);return s[Math.floor((s.length-1)*q)]};const p10=yearBuckets.map(a=>quant(a,.1)),p50=yearBuckets.map(a=>quant(a,.5)),p90=yearBuckets.map(a=>quant(a,.9)),labels=Array.from({length:f.years+1},(_,i)=>String(2026+i));document.getElementById("volLabel").textContent=pct(vol*100);document.getElementById("mcFacts").innerHTML=[["10. Perzentil",eur(p10.at(-1))],["Median",eur(p50.at(-1))],["90. Perzentil",eur(p90.at(-1))],["Simulationen",String(paths)]].map(x=>`<div class="fact"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");lineChart("mcChart",labels,[{name:"10 %",values:p10},{name:"Median",values:p50,bold:true},{name:"90 %",values:p90}])}
document.getElementById("volatility").oninput=renderMC;renderMC();

// GOALS
function estimatedNetProfit(){
  const settings=taxSettings();
  const positive=D.positions.filter(p=>p.pl>0);
  const raw=positive.reduce((a,p)=>a+p.pl*(1-p.taxExemption/100),0);
  let allowance=settings.allowance;
  let totalTax=0;
  positive.forEach(p=>{
    const taxablePotential=p.pl*(1-p.taxExemption/100);
    const share=raw?Math.min(allowance,settings.allowance*taxablePotential/raw):0;
    totalTax+=calculateTax(p.pl,p.taxExemption,share,settings).tax;
    allowance=Math.max(0,allowance-share);
  });
  return Math.max(0,positive.reduce((a,p)=>a+p.pl,0)-totalTax);
}
function goalHtml(current,target,label){const progress=Math.max(0,Math.min(100,current/target*100)),missing=Math.max(0,target-current);return `<div class="goal-card"><div class="big">${pct(progress)}</div><div class="goal-track"><span style="width:${progress}%"></span></div><p>${label}: ${eur(current)} · Noch ${eur(missing)} bis zum Ziel.</p></div>`}
function healthCalculation(){const shares=D.positions.map(p=>p.value/latest),hhi=shares.reduce((a,s)=>a+s*s,0),diversification=Math.max(0,100-(hhi-.125)*180),largest=Math.max(...shares)*100,concentration=Math.max(0,100-(largest-20)*2.2),performance=Math.max(0,Math.min(100,50+(latest/investedTotal-1)*350)),drawdown=Math.max(0,100-Math.abs((latest/high-1)*100)*8),savings=95,score=Math.round(diversification*.25+concentration*.2+performance*.25+drawdown*.2+savings*.1);return{score,diversification,concentration,performance,drawdown,savings}}
function renderGoals(){const pt=+document.getElementById("portfolioTarget").value||1,gt=+document.getElementById("profitTarget").value||1,net=estimatedNetProfit();document.getElementById("portfolioGoal").innerHTML=goalHtml(latest,pt,"Aktueller Depotwert");document.getElementById("profitGoal").innerHTML=goalHtml(profitTotal,gt,"Aktuelles Gewinnkonto");const h=healthCalculation();document.getElementById("healthScore").innerHTML=`<div class="health-main"><div class="score-ring" style="--score:${h.score*3.6}deg"><strong>${h.score}</strong><span>von 100</span></div><div class="score-list">${[["Diversifikation",h.diversification],["Konzentration",h.concentration],["Performance",h.performance],["Drawdown-Stabilität",h.drawdown],["Sparplandisziplin",h.savings]].map(x=>`<div class="score-line"><span>${x[0]}</span><strong>${Math.round(x[1])}</strong></div>`).join("")}</div></div>`;const credit=+document.getElementById("creditRate").value||1,holiday=+document.getElementById("holidayCost").value||1;document.getElementById("lifeGoals").innerHTML=`<div class="life-list"><div class="life-item"><span>Monatliche Kreditraten</span><strong>${nfmt(net/credit)}</strong></div><div class="life-item"><span>Monate Sparplan à 150 €</span><strong>${nfmt(net/150)}</strong></div><div class="life-item"><span>Familienurlaube</span><strong>${nfmt(net/holiday)}</strong></div><div class="life-item"><span>Geschätzter Nettogewinn</span><strong>${eur(net)}</strong></div></div>`}
["portfolioTarget","profitTarget","creditRate","holidayCost"].forEach(id=>document.getElementById(id).oninput=renderGoals);renderGoals();

// JOURNAL
function journalText(i){const v=D.depot[i],prev=i>0?D.depot[i-1]:null,change=prev===null?0:v-prev;if(D.notes[D.fullDates[i]])return D.notes[D.fullDates[i]];if(i===0)return"Erster dokumentierter Messpunkt des Portfolios.";if(change>1500)return`Starker Anstieg um ${eur(change)} gegenüber dem vorherigen Screenshot.`;if(change>0)return`Leichte positive Entwicklung um ${eur(change)}.`;if(change<-1500)return`Deutlicher Rückgang um ${eur(Math.abs(change))}.`;return`Leichte Korrektur um ${eur(Math.abs(change))}.`}
document.getElementById("journalTimeline").innerHTML=D.fullDates.slice().reverse().map((d,ri)=>{const i=D.fullDates.length-1-ri,prev=i>0?D.depot[i-1]:null,ch=prev===null?null:D.depot[i]-prev;return `<div class="journal-entry"><div class="date">${d}</div><div><div class="value">${eur(D.depot[i])}</div><span class="${ch===null?"":ch>=0?"pos":"neg"}">${ch===null?"Start":`${ch>=0?"+":""}${eur(ch)}`}</span></div><div class="story">${journalText(i)}</div></div>`}).join("");

// NAV + UI
document.querySelectorAll(".section-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".section-tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById("view-"+b.dataset.view).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})});
document.getElementById("learnMode").onchange=e=>document.body.classList.toggle("learning-on",e.target.checked);
document.getElementById("insightReset").onclick=showPortfolioInsight;document.getElementById("insightClose").onclick=()=>appLayout.classList.remove("insight-open");document.getElementById("insightLauncher").onclick=showPortfolioInsight;
const root=document.documentElement;document.getElementById("themeBtn").onclick=()=>{const dark=root.getAttribute("data-theme")==="dark";root.setAttribute("data-theme",dark?"light":"dark");localStorage.setItem("theme",dark?"light":"dark")};if(localStorage.getItem("theme")==="dark")root.setAttribute("data-theme","dark");
showPortfolioInsight();appLayout.classList.remove("insight-open");
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
