
const C=["#2563eb","#7c3aed","#0891b2","#16a34a","#ea580c","#dc2626","#4f46e5","#0f766e"];
const eur=v=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v);
const pct=v=>new Intl.NumberFormat("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)+" %";
const latest=D.depot.at(-1),start=D.depot[0],low=Math.min(...D.depot),high=Math.max(...D.depot),lastDelta=latest-D.depot.at(-2);
const allSeries={...D.core,...D.savings};
const insightPanel=document.getElementById("insightPanel");const appLayout=document.querySelector(".app-layout");

function insightOpen(){appLayout.classList.add("insight-open")}
function setInsight(type,title,html){document.getElementById("insightType").textContent=type;document.getElementById("insightTitle").textContent=title;document.getElementById("insightBody").innerHTML=html;insightOpen()}
function miniSpark(values,color="#2563eb"){const W=290,H=120,p=6,lo=Math.min(...values),hi=Math.max(...values),x=i=>p+i*(W-2*p)/Math.max(1,values.length-1),y=v=>p+(hi-v)*(H-2*p)/((hi-lo)||1);return `<svg class="insight-chart" viewBox="0 0 ${W} ${H}"><polyline points="${values.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function showPortfolioInsight(){const best=[...D.positions].sort((a,b)=>b.perf-a.perf)[0],worst=[...D.positions].sort((a,b)=>a.perf-b.perf)[0],largest=[...D.positions].sort((a,b)=>b.value-a.value)[0];setInsight("Portfolio Insight","Gesamtübersicht",`<div class="insight-section"><div class="insight-label">Aktueller Depotwert</div><div class="insight-value">${eur(latest)}</div><div class="insight-change ${lastDelta>=0?"pos":"neg"}">${lastDelta>=0?"+":""}${eur(lastDelta)} seit letztem Screenshot</div>${miniSpark(D.depot)}</div><div class="insight-section"><div class="insight-label">Kennzahlen</div><div class="insight-grid"><div class="insight-stat"><span>Seit Start</span><strong class="${latest-start>=0?"pos":"neg"}">${eur(latest-start)}</strong></div><div class="insight-stat"><span>Rendite</span><strong>${pct((latest/start-1)*100)}</strong></div><div class="insight-stat"><span>Abstand Hoch</span><strong>${pct((latest/high-1)*100)}</strong></div><div class="insight-stat"><span>Datenstand</span><strong>${D.meta.lastUpdate}</strong></div></div></div><div class="insight-section"><div class="insight-label">Einordnung</div><div class="insight-list"><div class="insight-list-row"><span>Größte Position</span><strong>${largest.name}</strong></div><div class="insight-list-row"><span>Stärkste Position</span><strong class="pos">${best.name}</strong></div><div class="insight-list-row"><span>Schwächste Position</span><strong class="neg">${worst.name}</strong></div></div></div>`)}
function showPositionInsight(name){document.querySelectorAll('.position-card').forEach(c=>c.classList.toggle('active',c.dataset.name===name));const p=D.positions.find(x=>x.name===name),arr=allSeries[name],peak=Math.max(...arr),trough=Math.min(...arr),weekly=arr.at(-1)-arr.at(-2),share=p.value/latest*100;setInsight("Position Insight",name,`<div class="insight-section"><div class="insight-label">Aktueller Wert</div><div class="insight-value">${eur(p.value)}</div><div class="insight-change ${p.perf>=0?"pos":"neg"}">${p.perf>=0?"+":""}${pct(p.perf)} seit Kauf</div>${miniSpark(arr,p.perf>=0?"#15803d":"#b91c1c")}</div><div class="insight-section"><div class="insight-grid"><div class="insight-stat"><span>Investiert</span><strong>${eur(p.invested)}</strong></div><div class="insight-stat"><span>Gewinn / Verlust</span><strong class="${p.pl>=0?"pos":"neg"}">${eur(p.pl)}</strong></div><div class="insight-stat"><span>Wochenänderung</span><strong class="${weekly>=0?"pos":"neg"}">${eur(weekly)}</strong></div><div class="insight-stat"><span>Depotanteil</span><strong>${pct(share)}</strong></div><div class="insight-stat"><span>Abstand Hoch</span><strong>${pct((p.value/peak-1)*100)}</strong></div><div class="insight-stat"><span>Bisheriges Tief</span><strong>${eur(trough)}</strong></div></div></div><div class="insight-section"><div class="insight-label">Stammdaten</div><div class="insight-list"><div class="insight-list-row"><span>WKN</span><strong>${p.wkn||"–"}</strong></div><div class="insight-list-row"><span>ISIN</span><strong>${p.isin||"–"}</strong></div>${p.quantity?`<div class="insight-list-row"><span>Stückzahl</span><strong>${p.quantity}</strong></div>`:""}${p.buyPrice?`<div class="insight-list-row"><span>Kaufkurs</span><strong>${eur(p.buyPrice)}</strong></div>`:""}</div></div>`)}
function showChartInsight(series,labels,i,globalIndex=null){const v=series.values[i],prev=i>0?series.values[i-1]:null,gi=globalIndex??i;setInsight("Chart Insight",series.name,`<div class="insight-section"><div class="insight-label">Ausgewählter Messpunkt</div><div class="insight-value">${eur(v)}</div><div class="insight-change ${prev===null?"":v-prev>=0?"pos":"neg"}">${prev===null?"Startpunkt":`${v-prev>=0?"+":""}${eur(v-prev)} zum vorherigen Punkt`}</div></div><div class="insight-section"><div class="insight-grid"><div class="insight-stat"><span>Datum</span><strong>${D.fullDates[gi]||labels[i]}</strong></div><div class="insight-stat"><span>Seit Start</span><strong>${pct((v/series.values[0]-1)*100)}</strong></div></div></div>${D.notes?.[D.fullDates[gi]]?`<div class="insight-note">${D.notes[D.fullDates[gi]]}</div>`:""}`)}
function showCategoryInsight(c){const total=D.categories.reduce((a,b)=>a+b.value,0),ps=D.positions.filter(p=>p.cat===c.name);setInsight("Category Insight",c.name,`<div class="insight-section"><div class="insight-label">Kategorienwert</div><div class="insight-value">${eur(c.value)}</div><div class="insight-change">${pct(c.value/total*100)} des Gesamtdepots</div></div><div class="insight-section"><div class="insight-label">Enthaltene Positionen</div><div class="insight-list">${ps.map(p=>`<div class="insight-list-row" data-position="${p.name}"><span>${p.name}</span><strong>${eur(p.value)}</strong></div>`).join("")}</div></div>`);document.querySelectorAll('[data-position]').forEach(el=>el.onclick=()=>showPositionInsight(el.dataset.position))}

function lineChart(id,labels,series,{percent=false,zero=false,globalOffset=0}={}){const svg=document.getElementById(id),W=+svg.viewBox.baseVal.width,H=+svg.viewBox.baseVal.height,p={l:64,r:18,t:18,b:42};let vals=series.flatMap(s=>s.values),lo=Math.min(...vals),hi=Math.max(...vals);if(zero){lo=Math.min(lo,0);hi=Math.max(hi,0)}const pad=(hi-lo)*.1||1;lo-=pad;hi+=pad;const x=i=>p.l+i*(W-p.l-p.r)/Math.max(1,labels.length-1),y=v=>p.t+(hi-v)*(H-p.t-p.b)/(hi-lo);let out="";for(let i=0;i<5;i++){const v=lo+i*(hi-lo)/4,yy=y(v);out+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="var(--line)"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end" fill="var(--muted)" font-size="10">${percent?pct(v):Math.round(v/1000)+"k"}</text>`}labels.forEach((d,i)=>{if(i===0||i===labels.length-1||i%3===0)out+=`<text x="${x(i)}" y="${H-14}" text-anchor="middle" fill="var(--muted)" font-size="10">${d}</text>`});series.forEach((s,si)=>{const points=s.values.map((v,i)=>`${x(i)},${y(v)}`).join(" ");out+=`<polyline points="${points}" fill="none" stroke="${C[si%C.length]}" stroke-width="${s.bold?3.4:2.4}"/>`;s.values.forEach((v,i)=>{out+=`<circle class="chart-point" data-series="${si}" data-index="${i}" cx="${x(i)}" cy="${y(v)}" r="8" fill="transparent"/><circle cx="${x(i)}" cy="${y(v)}" r="3" fill="${C[si%C.length]}" stroke="white"/>`})});svg.innerHTML=out;svg.querySelectorAll('.chart-point').forEach(point=>point.onclick=()=>{const si=+point.dataset.series,i=+point.dataset.index,s=series[si];showChartInsight(s,labels,i,globalOffset+i)})}
function hbars(id,rows,key,fmt,signed=false){
  const svg=document.getElementById(id),W=+svg.viewBox.baseVal.width,H=+svg.viewBox.baseVal.height;
  const padX=14,padY=10,rowH=(H-padY*2)/rows.length;
  const max=Math.max(...rows.map(r=>Math.abs(r[key])))||1;
  const left=padX,right=W-padX,center=(left+right)/2;
  let out="";
  rows.forEach((r,i)=>{
    const y=padY+i*rowH;
    const labelY=y+11;
    const trackY=y+18;
    const trackH=Math.max(7,Math.min(11,rowH-24));
    const value=r[key];
    const fullW=right-left;
    let x=left,w=Math.abs(value)/max*fullW,barColor="#2563eb";
    if(signed){
      const half=(fullW-10)/2;
      w=Math.abs(value)/max*half;
      x=value>=0?center+5:center-5-w;
      barColor=value>=0?"#15803d":"#b91c1c";
      out+=`<line class="bar-chart-zero" x1="${center}" y1="${trackY-2}" x2="${center}" y2="${trackY+trackH+2}"/>`;
      out+=`<rect class="bar-chart-track" x="${left}" y="${trackY}" width="${half}" height="${trackH}" rx="${trackH/2}"/><rect class="bar-chart-track" x="${center+5}" y="${trackY}" width="${half}" height="${trackH}" rx="${trackH/2}"/>`;
    }else{
      out+=`<rect class="bar-chart-track" x="${left}" y="${trackY}" width="${fullW}" height="${trackH}" rx="${trackH/2}"/>`;
    }
    out+=`<text class="bar-chart-label" x="${left}" y="${labelY}">${r.name}</text>`;
    out+=`<text class="bar-chart-value" x="${right}" y="${labelY}" text-anchor="end">${fmt(value)}</text>`;
    out+=`<rect x="${x}" y="${trackY}" width="${Math.max(w,2)}" height="${trackH}" rx="${trackH/2}" fill="${barColor}"/>`;
    out+=`<rect class="bar-hit" data-index="${i}" x="${left}" y="${y}" width="${fullW}" height="${rowH}" fill="transparent"/>`;
  });
  svg.innerHTML=out;
  svg.querySelectorAll(".bar-hit").forEach(hit=>hit.onclick=()=>{
    const r=rows[+hit.dataset.index];
    if(D.positions.some(p=>p.name===r.name))showPositionInsight(r.name);
    else setInsight("Chart Insight",r.name,`<div class="insight-value ${r[key]>=0?"pos":"neg"}">${fmt(r[key])}</div>`);
  });
}
function sparkline(values){const W=220,H=54,p=3,lo=Math.min(...values),hi=Math.max(...values),x=i=>p+i*(W-2*p)/(values.length-1),y=v=>p+(hi-v)*(H-2*p)/((hi-lo)||1);return `<svg class="spark" viewBox="0 0 ${W} ${H}"><polyline points="${values.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="#2563eb" stroke-width="2.4"/></svg>`}

document.getElementById("rangeLabel").textContent=D.dates[0]+"–"+D.meta.lastUpdate;document.getElementById("lastUpdate").textContent="Stand "+D.meta.lastUpdate;
document.getElementById("kpis").innerHTML=[["Aktueller Depotwert",eur(latest),"Stand "+D.meta.lastUpdate],["Seit Start",eur(latest-start),pct((latest/start-1)*100)],["Seit letztem Screenshot",eur(lastDelta),pct((latest/D.depot.at(-2)-1)*100)],["Erholung seit Tief",eur(latest-low),pct((latest/low-1)*100)]].map((x,i)=>`<article class="card kpi"><div class="label">${x[0]}</div><div class="value ${x[1].startsWith("-")?"neg":(i>0?"pos":"")}">${x[1]}</div><div class="hint">${x[2]}</div></article>`).join("");
lineChart("depotChart",D.dates,[{name:"Depotwert",values:D.depot,bold:true}]);
document.getElementById("weeklyKpis").innerHTML=[["Depotveränderung",eur(lastDelta)],["Monatsveränderung",eur(latest-D.monthly.at(-1).start)],["Bester Wert",D.weeklyChanges[0].name],["Schwächster Wert",D.weeklyChanges.at(-1).name]].map(x=>`<div class="mini-card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");
document.getElementById("ranking").innerHTML=`<div class="rank-list">${D.weeklyChanges.slice(0,3).map((r,i)=>`<div class="rank-item" data-name="${r.name}"><span>${i+1}. ${r.name}</span><strong class="${r.change>=0?"pos":"neg"}">${eur(r.change)}</strong></div>`).join("")}<div style="height:8px"></div>${D.weeklyChanges.slice(-3).reverse().map((r,i)=>`<div class="rank-item" data-name="${r.name}"><span>${i+1}. ${r.name}</span><strong class="${r.change>=0?"pos":"neg"}">${eur(r.change)}</strong></div>`).join("")}</div>`;document.querySelectorAll('.rank-item').forEach(el=>el.onclick=()=>showPositionInsight(el.dataset.name));
const normalized={};Object.entries(D.core).forEach(([k,v])=>normalized[k]=v.map(x=>x/v[0]*100));const names=Object.keys(normalized);document.getElementById("coreTabs").innerHTML='<button class="active" data-mode="all">Alle</button>'+names.map((n,i)=>`<button data-mode="${i}">${n}</button>`).join("");function drawCore(mode="all"){const s=mode==="all"?names.map(n=>({name:n,values:normalized[n]})):[{name:names[+mode],values:normalized[names[+mode]],bold:true}];lineChart("coreChart",D.dates,s);document.getElementById("coreLegend").innerHTML=s.map((x,i)=>`<span><i style="background:${C[i]}"></i>${x.name}</span>`).join("")}drawCore();document.querySelectorAll("#coreTabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#coreTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");drawCore(b.dataset.mode)});
document.getElementById("positionCards").innerHTML=D.positions.map(p=>{const arr=allSeries[p.name],peak=Math.max(...arr),dist=(p.value/peak-1)*100,weekly=arr.at(-1)-arr.at(-2);return `<div class="position-card" data-name="${p.name}"><h3>${p.name}</h3>${sparkline(arr)}<div class="row"><span>Aktueller Wert</span><strong>${eur(p.value)}</strong></div><div class="row"><span>Seit letzter Woche</span><strong class="${weekly>=0?"pos":"neg"}">${eur(weekly)}</strong></div><div class="row"><span>Abstand zum Hoch</span><strong class="${dist>=0?"pos":"neg"}">${pct(dist)}</strong></div></div>`}).join("");document.querySelectorAll('.position-card').forEach(c=>c.onclick=()=>showPositionInsight(c.dataset.name));
let runningMax=-Infinity,maxDD=0,maxDDIndex=0;const dd=D.depot.map((v,i)=>{runningMax=Math.max(runningMax,v);const d=(v/runningMax-1)*100;if(d<maxDD){maxDD=d;maxDDIndex=i}return d});lineChart("drawdownChart",D.dates,[{name:"Drawdown",values:dd,bold:true}],{percent:true,zero:true});document.getElementById("drawdownFacts").innerHTML=[["Größter Rückgang",pct(maxDD)],["Tiefpunkt",D.dates[maxDDIndex]],["Aktueller Abstand zum Hoch",pct((latest/high-1)*100)],["Hochpunkt",D.dates[D.depot.indexOf(high)]]].map(x=>`<div class="fact"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");
const sn=Object.keys(D.savings);document.getElementById("savingTabs").innerHTML=sn.map((n,i)=>`<button class="${i===0?"active":""}" data-i="${i}">${n}</button>`).join("");function drawSaving(i=0){const n=sn[i],v=D.savings[n],invested=D.contrib.at(-1),current=v.at(-1),gain=current-invested;lineChart("savingsChart",D.dates,[{name:n,values:v,bold:true},{name:"Einzahlungen",values:D.contrib}]);document.getElementById("savingFacts").innerHTML=[["Eingezahlt",eur(invested)],["Aktueller Wert",eur(current)],["Kursgewinn/-verlust",eur(gain)],["Rendite",pct(gain/invested*100)]].map(x=>`<div class="fact"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");showPositionInsight(n)}drawSaving();document.querySelectorAll("#savingTabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#savingTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");drawSaving(+b.dataset.i)});
hbars("monthlyChart",D.monthly.map(m=>({name:m.month.slice(5)+"/"+m.month.slice(2,4),value:m.change})),"value",eur,true);hbars("perfChart",D.positions,"perf",pct,true);hbars("plChart",D.positions,"pl",eur,true);
(function donut(){const svg=document.getElementById("donut"),cx=210,cy=155,r=100,sw=48,total=D.categories.reduce((a,b)=>a+b.value,0);let acc=0,out="";D.categories.forEach((c,i)=>{const f=c.value/total,len=2*Math.PI*r*f,off=-2*Math.PI*r*acc;out+=`<circle class="donut-segment" data-index="${i}" cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${C[i]}" stroke-width="${sw}" stroke-dasharray="${len} ${2*Math.PI*r-len}" stroke-dashoffset="${off}" transform="rotate(-90 ${cx} ${cy})"/>`;acc+=f});out+=`<text x="${cx}" y="${cy-4}" text-anchor="middle" fill="var(--muted)" font-size="13">Depotwert</text><text x="${cx}" y="${cy+24}" text-anchor="middle" fill="var(--ink)" font-size="21" font-weight="800">${Math.round(total/1000)} Tsd. €</text>`;svg.innerHTML=out;svg.querySelectorAll('.donut-segment').forEach(seg=>seg.onclick=()=>showCategoryInsight(D.categories[+seg.dataset.index]));document.getElementById("catLegend").innerHTML=D.categories.map((c,i)=>`<span><i style="background:${C[i]}"></i>${c.name} · ${pct(c.value/total*100)}</span>`).join("")})();
const qCounts={direct:0,summed:0,history:0};D.quality.forEach(q=>qCounts[q.status]++);document.getElementById("qualitySummary").innerHTML=[["Direkte Screenshots",qCounts.direct],["Summierte Werte",qCounts.summed],["Historienwerte",qCounts.history],["Messpunkte gesamt",D.quality.length]].map(x=>`<div class="mini-card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("");document.getElementById("qualityRows").innerHTML=D.quality.slice().reverse().map(q=>`<tr><td>${q.date}</td><td><span class="badge ${q.status}">${q.status}</span></td><td>${q.label}</td></tr>`).join("");
const total=D.positions.reduce((a,b)=>a+b.value,0);document.getElementById("positionRows").innerHTML=D.positions.map(p=>`<tr data-name="${p.name}" style="cursor:pointer"><td><strong>${p.name}</strong></td><td>${p.cat}</td><td>${eur(p.invested)}</td><td>${eur(p.value)}</td><td><span class="badge ${p.pl>=0?"pos":"neg"}">${p.pl>=0?"+":""}${eur(p.pl)}</span></td><td class="${p.perf>=0?"pos":"neg"}"><strong>${p.perf>=0?"+":""}${pct(p.perf)}</strong></td><td style="min-width:160px">${pct(p.value/total*100)}<div class="bar"><span style="width:${p.value/total*100}%"></span></div></td></tr>`).join("");document.querySelectorAll('#positionRows tr').forEach(r=>r.onclick=()=>showPositionInsight(r.dataset.name));

document.getElementById("insightReset").onclick=()=>{document.querySelectorAll(".position-card").forEach(c=>c.classList.remove("active"));showPortfolioInsight()};
document.getElementById("insightClose").onclick=()=>appLayout.classList.remove("insight-open");
document.getElementById("insightLauncher").onclick=()=>{showPortfolioInsight();appLayout.classList.add("insight-open")};
const root=document.documentElement;document.getElementById("themeBtn").onclick=()=>{const dark=root.getAttribute("data-theme")==="dark";root.setAttribute("data-theme",dark?"light":"dark");localStorage.setItem("theme",dark?"light":"dark")};if(localStorage.getItem("theme")==="dark")root.setAttribute("data-theme","dark");
showPortfolioInsight();appLayout.classList.remove("insight-open");if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
