(() => {
const qFallback={"BNP SX7E":250,"AGIF Artificial Intelligence":0.8645,"UBS Security Equity":1.5794,"DWS Smart Industrial":1.0371,"DWS ESG Akkumula":8,"DWS Top Dividende":120,"DWS ESG Stiftungsfonds":480,"DWS STR-DB Balanced":400};
D.positions.forEach(p=>{if(!Number.isFinite(p.quantity))p.quantity=qFallback[p.name]||0});
const fixedCore=D.positions.filter(p=>!Object.prototype.hasOwnProperty.call(D.savings,p.name)).reduce((a,p)=>a+p.invested,0);
const investedHistory=D.contrib.map(v=>fixedCore+v*Object.keys(D.savings).length);
const profitHistory=D.depot.map((v,i)=>v-investedHistory[i]);
const currentInvested=investedHistory.at(-1),currentProfit=D.depot.at(-1)-currentInvested;
const allHigh=Math.max(...D.depot),highI=D.depot.indexOf(allHigh),beI=profitHistory.findIndex(v=>v>=0);
const allPositionSeries={...D.core,...D.savings};

function prepareCompactLayout(){
 const dashboard=document.getElementById("view-dashboard");
 const firstSplit=document.getElementById("depotChart")?.closest("section.grid");
 const allocationCard=document.getElementById("donut")?.closest("article");
 if(firstSplit){firstSplit.className="grid full-width-section";firstSplit.querySelector("article")?.classList.add("hero-chart-card");allocationCard?.remove()}
 document.getElementById("milestoneGrid")?.closest("section.grid")?.remove();
 const holdingsSection=document.getElementById("holdingsRows")?.closest("section.grid");
 if(holdingsSection){holdingsSection.className="grid full-width-section position-analysis-section";holdingsSection.innerHTML=`<article class="card position-analysis-card"><div class="card-head"><div><h2>Positionen</h2><span>Position wählen und durch die Messpunkte wischen</span></div><button class="explain-btn" data-explain="positions">ⓘ</button></div><div id="positionHistoryTabs" class="tabs position-history-tabs"></div><svg id="positionHistoryChart" class="chart tall interactive-chart" viewBox="0 0 1100 390"></svg><div id="positionHistoryFacts" class="fact-grid holding-facts compact-facts"></div><div class="gesture-hint">↔ Wischen oder tippen: Datum, Wert und Veränderung erscheinen im Chart Insight.</div><div class="learn-box" data-learning="positions"></div></article>`}
 const wealthSection=document.getElementById("wealthBuildChart")?.closest("section.grid");
 const allocationHistoryCard=document.getElementById("allocationHistoryChart")?.closest("article");
 wealthSection?.remove();
 document.getElementById("positionCards")?.closest("section.grid")?.remove();
 const coreSection=document.getElementById("coreChart")?.closest("section.card");
 const savingsSection=document.getElementById("savingsChart")?.closest("section.grid");
 const advanced=document.createElement("details");advanced.className="analysis-drawer";advanced.innerHTML=`<summary><span><strong>Weitere Analysen</strong><small>Struktur, Positionsvergleich, Sparpläne und Monatswerte</small></span><b>Öffnen</b></summary><div class="advanced-content"></div>`;
 const content=advanced.querySelector(".advanced-content");
 if(allocationHistoryCard||allocationCard){const s=document.createElement("section");s.className="grid split-even compact-analysis-grid";if(allocationHistoryCard)s.appendChild(allocationHistoryCard);if(allocationCard)s.appendChild(allocationCard);content.appendChild(s)}
 if(coreSection)content.appendChild(coreSection);if(savingsSection)content.appendChild(savingsSection);dashboard?.appendChild(advanced);
 document.querySelectorAll('.explain-btn').forEach(b=>{if(!b.dataset.compactBound){b.dataset.compactBound="1";b.addEventListener('click',()=>typeof showExplanation==='function'&&showExplanation(b.dataset.explain))}});
}
prepareCompactLayout();

const setInsightSafe=(type,title,html)=>typeof setInsight==="function"&&setInsight(type,title,html);
const dateLabel=i=>D.fullDates?.[i]||D.dates[i];
const posForName=name=>D.positions.find(p=>p.name===name);
function holdingHtml(p){const q=p?.quantity||0,course=q?p.value/q:0,buy=q?p.invested/q:(p?.buyPrice||0);return `<div class="insight-section"><div class="insight-label">Aktueller Bestand</div><div class="insight-grid"><div class="insight-stat"><span>Anteile / Stück</span><strong>${nfmt(q)}</strong></div><div class="insight-stat"><span>Aktueller Kurs</span><strong>${eur(course)}</strong></div><div class="insight-stat"><span>Ø Einstand</span><strong>${eur(buy)}</strong></div><div class="insight-stat"><span>Positionswert</span><strong>${eur(p?.value||0)}</strong></div></div></div>`}
function showDepotPoint(i){const v=D.depot[i],prev=i?D.depot[i-1]:null,profit=profitHistory[i],peak=Math.max(...D.depot.slice(0,i+1));setInsightSafe("Chart Insight",`Gesamtdepot · ${dateLabel(i)}`,`<div class="insight-section"><div class="insight-label">Depotwert am Messpunkt</div><div class="insight-value">${eur(v)}</div><div class="${prev===null?"":v-prev>=0?"pos":"neg"}">${prev===null?"Erster Messpunkt":`${v-prev>=0?"+":""}${eur(v-prev)} zum vorherigen Messpunkt`}</div></div><div class="insight-section"><div class="insight-grid"><div class="insight-stat"><span>Investiert</span><strong class="break-even-value">${eur(investedHistory[i])}</strong></div><div class="insight-stat"><span>Buchgewinn</span><strong class="${profit>=0?'pos':'neg'}">${eur(profit)}</strong></div><div class="insight-stat"><span>Bisheriges Hoch</span><strong>${eur(peak)}</strong></div><div class="insight-stat"><span>Abstand zum Hoch</span><strong>${pct((v/peak-1)*100)}</strong></div></div></div>`)}
function showPositionPoint(name,i){const values=allPositionSeries[name],p=posForName(name),v=values[i],prev=i?values[i-1]:null,peak=Math.max(...values.slice(0,i+1));setInsightSafe("Chart Insight",`${name} · ${dateLabel(i)}`,`<div class="insight-section"><div class="insight-label">Positionswert am Messpunkt</div><div class="insight-value">${eur(v)}</div><div class="${prev===null?"":v-prev>=0?"pos":"neg"}">${prev===null?"Erster Messpunkt":`${v-prev>=0?"+":""}${eur(v-prev)} zum vorherigen Messpunkt`}</div><div class="insight-grid"><div class="insight-stat"><span>Seit Start</span><strong>${pct((v/values[0]-1)*100)}</strong></div><div class="insight-stat"><span>Abstand damaliges Hoch</span><strong>${pct((v/peak-1)*100)}</strong></div></div></div>${holdingHtml(p)}`)}
function nearestIndex(evt,svg,count,pad){const r=svg.getBoundingClientRect(),clientX=evt.clientX??evt.touches?.[0]?.clientX,local=(clientX-r.left)/r.width*svg.viewBox.baseVal.width;return Math.max(0,Math.min(count-1,Math.round((local-pad.l)/(svg.viewBox.baseVal.width-pad.l-pad.r)*(count-1))))}
function bindScrubber(svg,count,pad,onChange){let active=false,last=-1;const update=e=>{if(!active&&e.type!=="pointermove")return;const i=nearestIndex(e,svg,count,pad);if(i===last)return;last=i;onChange(i);if(navigator.vibrate&&active)navigator.vibrate(5);if(e.cancelable)e.preventDefault()};svg.addEventListener("pointerdown",e=>{active=true;svg.setPointerCapture?.(e.pointerId);update(e)});svg.addEventListener("pointermove",e=>{if(e.pointerType==="mouse"||active)update(e)});svg.addEventListener("pointerup",()=>active=false);svg.addEventListener("pointercancel",()=>active=false)}

function makeTooltipX(x,W,pad,width=176){return Math.max(pad.l,Math.min(W-pad.r-width,x-width/2))}
function initDepotChart(){
 const svg=document.getElementById("depotChart"),W=1100,H=390,p={l:72,r:24,t:34,b:48};svg.setAttribute("viewBox",`0 0 ${W} ${H}`);svg.classList.add("interactive-chart");
 const vals=[...D.depot,...investedHistory],lo=Math.min(...vals)*.995,hi=Math.max(...vals)*1.005,x=i=>p.l+i*(W-p.l-p.r)/(D.dates.length-1),y=v=>p.t+(hi-v)*(H-p.t-p.b)/(hi-lo);
 let out=`<defs><linearGradient id="gainFill55" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#16a34a" stop-opacity=".24"/><stop offset="1" stop-color="#16a34a" stop-opacity=".03"/></linearGradient></defs>`;
 for(let i=0;i<5;i++){const v=lo+i*(hi-lo)/4,yy=y(v);out+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="var(--line)"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end" fill="var(--muted)" font-size="10">${Math.round(v/1000)}k</text>`}
 for(let i=0;i<D.depot.length-1;i++)out+=`<polygon points="${x(i)},${y(D.depot[i])} ${x(i+1)},${y(D.depot[i+1])} ${x(i+1)},${y(investedHistory[i+1])} ${x(i)},${y(investedHistory[i])}" fill="url(#gainFill55)"/>`;
 out+=`<polyline points="${investedHistory.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="#b45309" stroke-width="2.5" stroke-dasharray="7 6"/><polyline points="${D.depot.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="#2563eb" stroke-width="3.5"/>`;
 D.depot.forEach((v,i)=>out+=`<circle cx="${x(i)}" cy="${y(v)}" r="3.5" fill="#2563eb" stroke="white"/>`);
 out+=`<circle cx="${x(highI)}" cy="${y(D.depot[highI])}" r="6" fill="#7c3aed" stroke="white" stroke-width="2"/><text x="${x(highI)}" y="${y(D.depot[highI])-12}" text-anchor="middle" fill="#a78bfa" font-size="11" font-weight="800">Allzeithoch</text>`;
 if(beI>=0)out+=`<line x1="${x(beI)}" y1="${p.t}" x2="${x(beI)}" y2="${H-p.b}" stroke="#f59e0b" stroke-dasharray="3 4"/><text x="${x(beI)+5}" y="${p.t+12}" fill="#f59e0b" font-size="10" font-weight="800">Break-even</text>`;
 D.dates.forEach((d,i)=>{if(i===0||i===D.dates.length-1||i%3===0)out+=`<text x="${x(i)}" y="${H-15}" text-anchor="middle" fill="var(--muted)" font-size="10">${d}</text>`});
 out+=`<g transform="translate(${p.l},12)"><line x1="0" y1="0" x2="24" y2="0" stroke="#2563eb" stroke-width="3"/><text x="30" y="4" fill="var(--muted)" font-size="11">Depotwert</text><line x1="105" y1="0" x2="129" y2="0" stroke="#b45309" stroke-width="2.5" stroke-dasharray="7 5"/><text x="135" y="4" fill="var(--muted)" font-size="11">Investiert / Break-even</text></g>`;
 out+=`<g class="scrub-cursor"><line class="scrub-line" y1="${p.t}" y2="${H-p.b}"/><circle class="scrub-cap" cy="${p.t}" r="5"/><circle class="scrub-handle" r="7"/><rect class="scrub-tooltip" y="${p.t+10}" width="176" height="34" rx="9"/><text class="scrub-tooltip-text" y="${p.t+32}" text-anchor="middle"></text></g>`;
 svg.innerHTML=out;
 const cursor=svg.querySelector('.scrub-cursor'),line=cursor.querySelector('.scrub-line'),cap=cursor.querySelector('.scrub-cap'),handle=cursor.querySelector('.scrub-handle'),box=cursor.querySelector('.scrub-tooltip'),txt=cursor.querySelector('.scrub-tooltip-text');
 const update=i=>{const xx=x(i),yy=y(D.depot[i]),bx=makeTooltipX(xx,W,p);line.setAttribute('x1',xx);line.setAttribute('x2',xx);cap.setAttribute('cx',xx);handle.setAttribute('cx',xx);handle.setAttribute('cy',yy);box.setAttribute('x',bx);txt.setAttribute('x',bx+88);txt.textContent=`${D.dates[i]} · ${eur(D.depot[i])}`;updateStatus(i);showDepotPoint(i)};
 update(D.depot.length-1);bindScrubber(svg,D.depot.length,p,update);
}

function updateStatus(i){const strip=document.getElementById('breakEvenFacts');if(!strip)return;const v=D.depot[i],invested=investedHistory[i],profit=profitHistory[i],peak=Math.max(...D.depot.slice(0,i+1)),gap=v-peak;strip.querySelector('[data-status="current"]')?.replaceChildren(document.createTextNode(eur(v)));strip.querySelector('[data-status="invested"]')?.replaceChildren(document.createTextNode(eur(invested)));const p=strip.querySelector('[data-status="profit"]');if(p){p.textContent=eur(profit);p.className=profit>=0?'pos':'neg'}const g=strip.querySelector('[data-status="high"]');if(g){g.textContent=gap===0?'Rekord':eur(gap);g.className=gap<0?'neg':'pos'}}
const gap=D.depot.at(-1)-allHigh,breakFacts=document.getElementById("breakEvenFacts");
if(breakFacts){const nextThreshold=[1000,2500,5000,7500,10000].find(t=>currentProfit<t);breakFacts.className="portfolio-status-strip";breakFacts.innerHTML=`<div class="status-main"><span>Aktuell</span><strong data-status="current">${eur(D.depot.at(-1))}</strong></div><div><span>Investiert</span><strong data-status="invested">${eur(currentInvested)}</strong></div><div><span>Buchgewinn</span><strong data-status="profit" class="${currentProfit>=0?'pos':'neg'}">${eur(currentProfit)}</strong></div><div><span>Zum Allzeithoch</span><strong data-status="high" class="${gap<0?'neg':'pos'}">${gap===0?'Rekord':eur(gap)}</strong></div><details class="milestone-popover"><summary>Meilensteine</summary><div><p>Break-even: <b>${beI>=0?D.fullDates[beI]:'noch nicht'}</b></p><p>Allzeithoch: <b>${eur(allHigh)} · ${D.fullDates[highI]}</b></p><p>${nextThreshold?`Nächstes Ziel: <b>${eur(nextThreshold)} Gewinn</b> · noch ${eur(nextThreshold-currentProfit)}`:'Gewinnziel 10.000 € erreicht'}</p></div></details>`}
initDepotChart();

let selectedPosition=D.positions[0].name;const tabs=document.getElementById("positionHistoryTabs");if(tabs)tabs.innerHTML=D.positions.map((p,i)=>`<button class="${i===0?'active':''}" data-name="${p.name}">${p.name}</button>`).join("");
function initPositionChart(name){const svg=document.getElementById("positionHistoryChart"),values=allPositionSeries[name],W=1100,H=390,p={l:72,r:24,t:28,b:48},lo=Math.min(...values)*.985,hi=Math.max(...values)*1.015,x=i=>p.l+i*(W-p.l-p.r)/(values.length-1),y=v=>p.t+(hi-v)*(H-p.t-p.b)/((hi-lo)||1);let out="";for(let i=0;i<5;i++){const v=lo+i*(hi-lo)/4,yy=y(v);out+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="var(--line)"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end" fill="var(--muted)" font-size="10">${Math.round(v)} €</text>`}out+=`<polyline points="${values.map((v,i)=>`${x(i)},${y(v)}`).join(" ")}" fill="none" stroke="#2563eb" stroke-width="3.5"/>`;values.forEach((v,i)=>out+=`<circle cx="${x(i)}" cy="${y(v)}" r="3.5" fill="#2563eb" stroke="white"/>`);D.dates.forEach((d,i)=>{if(i===0||i===D.dates.length-1||i%3===0)out+=`<text x="${x(i)}" y="${H-15}" text-anchor="middle" fill="var(--muted)" font-size="10">${d}</text>`});out+=`<g class="scrub-cursor"><line class="scrub-line" y1="${p.t}" y2="${H-p.b}"/><circle class="scrub-cap" cy="${p.t}" r="5"/><circle class="scrub-handle" r="7"/><rect class="scrub-tooltip" y="${p.t+10}" width="176" height="34" rx="9"/><text class="scrub-tooltip-text" y="${p.t+32}" text-anchor="middle"></text></g>`;svg.innerHTML=out;const cursor=svg.querySelector('.scrub-cursor'),line=cursor.querySelector('.scrub-line'),cap=cursor.querySelector('.scrub-cap'),handle=cursor.querySelector('.scrub-handle'),box=cursor.querySelector('.scrub-tooltip'),txt=cursor.querySelector('.scrub-tooltip-text');const update=i=>{const xx=x(i),yy=y(values[i]),bx=makeTooltipX(xx,W,p);line.setAttribute('x1',xx);line.setAttribute('x2',xx);cap.setAttribute('cx',xx);handle.setAttribute('cx',xx);handle.setAttribute('cy',yy);box.setAttribute('x',bx);txt.setAttribute('x',bx+88);txt.textContent=`${D.dates[i]} · ${eur(values[i])}`;showPositionPoint(name,i)};update(values.length-1);bindScrubber(svg,values.length,p,update);const pos=posForName(name),q=pos.quantity||0,course=q?pos.value/q:0,buy=q?pos.invested/q:(pos.buyPrice||0),facts=document.getElementById("positionHistoryFacts");facts.innerHTML=[["Anteile",nfmt(q)],["Kurs",eur(course)],["Ø Einstand",eur(buy)],["Positionswert",eur(pos.value)],["G/V",`${eur(pos.pl)} · ${pct(pos.perf)}`],["Kategorie",pos.cat]].map(x=>`<div class="fact"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join("")}
initPositionChart(selectedPosition);tabs?.querySelectorAll("button").forEach(b=>b.onclick=()=>{tabs.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");selectedPosition=b.dataset.name;initPositionChart(selectedPosition)});

const ah={"Aktien Europa":D.core["BNP SX7E"],"Aktien Themen":D.dates.map((_,i)=>Object.values(D.savings).reduce((a,s)=>a+s[i],0)),"Aktien übergreifend":D.dates.map((_,i)=>D.core["DWS ESG Akkumula"][i]+D.core["DWS Top Dividende"][i]),"Multi Asset":D.dates.map((_,i)=>D.core["DWS ESG Stiftungsfonds"][i]+D.core["DWS STR-DB Balanced"][i])};
if(document.getElementById("allocationHistoryChart")){lineChart("allocationHistoryChart",D.dates,Object.entries(ah).map(([name,values])=>({name,values})));document.getElementById("allocationHistoryLegend").innerHTML=Object.keys(ah).map((n,i)=>`<span><i style="background:${C[i]}"></i>${n}</span>`).join("")}
})();